### ISSUE TITLE
Prototipação > [Página Home] Escolher paleta de cores para a Home.

### ISSUE THREAD

**Issue by ManoMax** [codexjr-dev/dashboard-codex-ui-designers#13]
# OVERVIEW 
- Para avançar no desenvolvimento da Página Home, é interessante que o design atual da tela em produção possua uma paleta de cores condizentes ao sistema e que façam esse tipo de referência ao ambiente do Projexa;

# TASK
- [x] Escolher paleta de cores para a Home.
- [x] Apresentar opções para os clientes e discorrer a respeito delas;
- [x] Coletar opiniões e trabalhar em cima das escolhas.
