### ISSUE TITLE
Prototipação > Criar Página para o Projeto.

### ISSUE THREAD

**Issue by ManoMax** [codexjr-dev/dashboard-codex-ui-designers#14]
# OVERVIEW 
- Devido a necessidade de aprimorar a qualidade de informação de visualizações, além de aumentar o número de informações exibidas, está ficando cada vez mais necessário que uma Página para cada projeto seja existente no sistema;
- Sendo assim, construa uma Página de Visualização de Projeto que possua os seguintes componentes:
  - Título com: `Projeto: <Nome do Projeto>`
  - Campo com a `Descrição` do Projeto;
  - Campos com `Data de Inicio` e `Data de Término`;
  - `Tags` do Projeto (geralmente são: Backend, Frontend, Mobile, Wordpress, etc);
  - `Time` envolvido (criar alguma estratégia para visualizar tanto o nome do membro, quanto a função dele no projeto);
  - `Informações do cliente`:
    - `Nome`;
    - `Email`;
    - `Telefone`;
  - `Link do contrato`;
  - `Botão para sair da página`;

# TASK
- [ ] Construir uma Página de Visualização de Projeto que possua os seguintes componentes:
  - [x] Esqueleto básico da página;
  - [x] `Botão para sair da página`;
  - [x] Título com: `Projeto: <Nome do Projeto>`
  - [x] `Informações do Projeto`:
    - [x] `Descrição`;
    - [x] `Datas` (Data de Início e Data de Término);
    - [x] `Tags`(geralmente são: Backend, Frontend, Mobile, Wordpress, etc);
  - [x] `Informações do Time`:
    - [x] `Nome` de cada integrante;
    - [x] `Função` de cada integrante;
  - [x] `Informações do cliente`:
    - [x] `Nome`;
    - [x] `Email`;
    - [x] `Telefone`;
    - [x] `Link do contrato`;

**Comment by carlos-lucenag** [comment]
Modificamos os checkboxes adaptando-os à nossa estrutura atual de realização da tarefa.
