### ISSUE TITLE
Prototipação > Retornar informações quanto a migração de ambiente Miro p/ Figma.

### ISSUE THREAD

**Issue by ManoMax** [codexjr-dev/dashboard-codex-ui-designers#17]
# OVERVIEW 
- Após solicitar a prototipação base criada por Lucas Anthony, foi realizada uma cópia desse protótipo (presente no Miro) para a Organização Miro da CodeX. No entanto, sabemos que, para o contexto de protipação de telas web, a plataforma Figma é muito mais utilizada e recomendada devido as ferramentas e proposta do sistema ali presente.

# TASK
- [x] Encontrar soluções para essa transferência de conteúdos, do Miro para o Figma;
- [x] Informar as soluções existentes na Daily;
- [x] Caso seja possível realizar facilmente, migrar o projeto para Figma utilizando algum e-mail @codexjr.

# Links:
- Projeto no Miro: https://miro.com/app/board/uXjVMw6Uprs=/
