### ISSUE TITLE
Prototipação > Atualizar os ícones dos cards da Página de Projetos.

### ISSUE THREAD

**Issue by ManoMax** [codexjr-dev/dashboard-codex-ui-designers#4]
# OVERVIEW 
- Após a Sprint [09.2023.s1](https://github.com/orgs/codexjr-dev/projects/34/views/1?filterQuery=sprint%3A%2209.2023.s1%22), ícones foram adicionados aos botões da Página de Projetos;
- Desse modo, será necessário atualizar a Prototipação para que, assim como o sistema, o design sobre tais botões fique ainda mais intuitivo.

# TASK
- [x] No contexto de Liderança, adicionar um ícone no botão de `adicionar atualização` do projeto;
- [x] No contexto de Liderança, adicionar um ícone no botão de `visualizar atualização` projeto;
- [x] No contexto de Liderança, adicionar um ícone no botão de `visualizar` projeto;
- [x] No contexto de Liderança, adicionar um ícone no botão de `editar` projeto;
- [x] No contexto de Liderança, adicionar um ícone no botão de `excluir` projeto;
- [x] No contexto de Assessor, adicionar um ícone no botão de `visualizar` projeto;
- [x] No contexto de Assessor, adicionar um ícone no botão de `editar` projeto;
- [x] No contexto de Assessor, adicionar um ícone no botão de `excluir` projeto;
