### ISSUE TITLE
Prototipação > Desenvolver a página de Configurações.

### ISSUE THREAD

**Issue by ManoMax** [codexjr-dev/dashboard-codex-ui-designers#7]
# OVERVIEW 
- A partir do novo botão da NavBar, `Configuração`, lideranças do sistema poderá ter acesso a um novo ambiente de configuração do Projexa.
- Essas configurações gerais serão:
  - Configurar o nome do sistema (título exibido no Tab Bar do Navegador);
  - Ícone do sistema (ícone exibido no Tab Bar do Navegador);
  - Nome da EJ (visível na Nav Bar do sistema);
  - Nomes e quantidade de Diretorias (listadas ao criar e editar algum membro);
  - Cargos dos membros (listadas ao criar e editar algum membro - atualmente é chamado como função do membro);
  - Identidade de cor do sistema (inicialmente, só as cores da Navbar e Background das páginas);

- Curiosidades fora dessa Issue:
  - O botão de configuração será semelhante aos demais botões e
  - Ao final da NavBar, existirá o botão de `Logoff` (diferente dos demais botões).
  - Além disso, somente lideranças verão o botão da página de `Configurações`;
  - Mas somente a página de `Configurações` deve ser levada em conta nessa Task.
  - A atualização de NavBar pertence a outra Issue.

# TASK
- [ ] Criar a Página de `Configurações`, possuindo os seguintes campos:
  - [ ] Campo de Texto: Configurar o nome do sistema;
  - [ ] Input de imagem: Ícone do sistema;
  - [ ] Campo de Texto: Nome da EJ;
  - [ ] Campo de Texto + Listagem dos nomes já cadastrados: Cadastrar/Remover Diretoria (discutir estratégia de como funcionará);
  - [ ] Campo de Texto + Listagem dos nomes já cadastrados: Cargos dos membros (discutir estratégia de como funcionará);
  - [ ] Seleção de cor: Cor da Navbar
  - [ ] Seleção de cor: Cor do Background das Páginas;
