### ISSUE TITLE
Prototipação > Atualizar página Home do Sistema.

### ISSUE THREAD

**Issue by ManoMax** [codexjr-dev/dashboard-codex-ui-designers#8]
# OVERVIEW 
- Ao acessar o sistema pela primeira vez, o usuário visualiza um ambiente com dois tipos de formatação diferentes, dependendo do navegador utilizado.
- No Mozilla, o sistema identifica uma imagem de fundo, no entanto, os botões cobrem a maior parte da tela e a parte textual também cobre a mesma proporção;
- No Chrome, o sistema não identifica alguma imagem e os botões ficam em um tamanho reduzido, mas o texto cobre a maior parte da tela, além de que o texto, devido a coloração parecida com o backgroud, fica quase invisível para o usuário.

# TASK
- [ ] Atualize o texto na tela inicial para algo menor, mais intuitivo e objetivo sobre o sistema;
- [ ] Padronize os botões, para algo mais centralizado e com melhor UI UX;
- [ ] Escolher uma imagem para a tela principal;
- [ ] Escolher paleta de cores para a Home;
