### ISSUE TITLE
Prototipação > Atualizar os ícones dos cards do Modal de Visualizar Atualizações.

### ISSUE THREAD

**Issue by ManoMax** [codexjr-dev/dashboard-codex-ui-designers#9]
# OVERVIEW 
- Para melhorar a intuitividade do sistema, no Modal de Visualizar Atualizações, é interessante que existam ícones similares ao das demais páginas, no entanto, indicando as funcionalidades `Abrir Link`, `Baixar Imagem` e `Excluir atualização`;
- Também para melhorar a experiência do usuário, será interessante que os botões tenham cores similares as demais páginas.

# TASK
- [x] Adicionar ícones no botão `Abrir Link`, no Contexto de Liderança;
- [x] Adicionar ícones no botão `Baixar Imagem`, no Contexto de Liderança;
- [x] Adicionar ícones no botão `Excluir atualização`, no Contexto de Liderança;
- [x] Adicionar ícones no botão `Abrir Link`, no Contexto de Assessor;
- [x] Adicionar ícones no botão `Baixar Imagem`, no Contexto de Assessor;
- [x] Adicionar ícones no botão `Excluir atualização`, no Contexto de Assessor;
- [x] Atualizar cores dos botões no Contexto de Liderança;
- [x] Atualizar cores dos botões no Contexto de Assessor;
